server:
  port: 8081

#开发配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.154.137:3306/godzilla?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    resources:
  static-locations: classpath:/static/,classpath:/static/,classpath:/resources/,classpath:/META-INF/resources/


config:
  jiraPath:
  userName:
  pswd:


security:
  basic:
    enabled: false
  headers:
    frame: false
